Traceback (most recent call last):
  File "C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\train.py", line 54, in <module>
    train_loss = train_one_epoch()
  File "C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\train.py", line 30, in train_one_epoch
    for x, y in train_loader:
                ^^^^^^^^^^^^
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\torch\utils\data\dataloader.py", line 733, in __next__
    data = self._next_data()
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\torch\utils\data\dataloader.py", line 789, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "C:\Users\visha\AppData\Roaming\Python\Python313\site-packages\torch\utils\data\_utils\fetch.py", line 52, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "C:\Users\visha\Downloads\ML_ASSIGNMENT_AYNA\dataset.py", line 40, in __getitem__
    raise KeyError(f"Missing expected keys in entry: {entry}")
KeyError: "Missing expected keys in entry: {'input_polygon': 'triangle.png', 'colour': 'blue', 'output_image': 'blue_triangle.png'}"
